DROP TABLE usuario CASCADE CONSTRAINTS;
DROP TABLE motorista CASCADE CONSTRAINTS;
DROP TABLE empresa CASCADE CONSTRAINTS;
DROP TABLE carro CASCADE CONSTRAINTS;

DROP SEQUENCE SQ_USUARIO_RM;
DROP SEQUENCE SQ_MOTORISTA;
DROP SEQUENCE SQ_EMPRESA;
DROP SEQUENCE SQ_CARRO;